In [1]:
import numpy as np
from datetime import datetime
import time

In [4]:
#Вводиться число n. Розставити 1 та 0 у шаховому порядку,починаючи з 1 в матриці розміром nхn, використовуючи слайсінг.
def task_2(): 
    n = int(input())
    start_time = datetime.now()
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if (i + j) % 2:
                text = text + "0"
            else:
                text = text + "1"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    print(datetime.now() - start_time)
    return text

In [5]:
def task_2np():
    n = int(input())
    start_time = datetime.now()
    Z = np.zeros((n,n), dtype=int)
    Z[1::2,::2] = 1
    Z[::2,1::2] = 1
    print(datetime.now() - start_time)
    return Z

In [7]:
task_2()

5
[[10101]
 [01010]
 [10101]
 [01010]
 [10101]]
0:00:00


'[[10101]\n [01010]\n [10101]\n [01010]\n [10101]]'

In [8]:
task_2np()

5
0:00:00


array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [9]:
# Вводяться числа n і m. Вивести масив розміру n на m, в якому упершому рядку (рядок з нулевим індексом)
# йдуть числа від 0 до m-1, а всі інші елементи матриці дорівнюють 0.
def task_4(): 
    n,m=map(int,input().split())
    count = 0 
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if i==0 and count < m:
                text = text + str(count)
                count = count+1
            else:
                text = text + "0"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

In [10]:
def task_4np():
    n,m=map(int,input().split())
    Z = np.zeros((n,n), dtype=int)
    P = np.arange(m)
    if m < n:
        Z[0, 0:m] = P[0:m] 
    if m >= n:
        Z[0, 0:n] = P[0:n]
    return Z

In [11]:
task_4()

3 4
[[012]
 [000]
 [000]]


'[[012]\n [000]\n [000]]'

In [12]:
task_4np()

3 4


array([[0, 1, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
# Вводиться число n. Вивести масив розміру n на n, в якому в рядках з парними індексами стоять 1, а в інших – 0.
def task_5(): 
    n = int(input()) 
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if i%2:
                text = text + "0"
            else:
                text = text + "1"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

In [14]:
def task_5np():
    n = int(input())
    Z = np.ones((n,n), dtype=int)
    Z[1::2] = 0
    return Z

In [15]:
task_5()

5
[[11111]
 [00000]
 [11111]
 [00000]
 [11111]]


'[[11111]\n [00000]\n [11111]\n [00000]\n [11111]]'

In [16]:
task_5np()

5


array([[1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [17]:
# З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульвих елементів.
def task_8():
    a = list(map(int,input().split()))
    zero=0
    nzero=0
    for i in range(len(a)):
        if a[i] == 0:
            zero=zero+1
        else:
            nzero=nzero+1
    print("Нулів: ", zero)
    print("Не нулів: ", nzero)
    return a

In [18]:
def task_8np():
    a = list(map(int,input().split()))
    nzero=np.count_nonzero(a)
    zero=len(a) - nzero
    print("Нулів: ", zero)
    print("Не нулів: ", nzero)
    return a

In [19]:
task_8()

3 4 0 9 8 2 4 0 8 4 0
Нулів:  3
Не нулів:  8


[3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0]

In [20]:
task_8np()

3 4 0 9 8 2 4 0 8 4 0
Нулів:  3
Не нулів:  8


[3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0]

In [21]:
# Вводиться число n. Створити масив значень від n до 0.
def task_9():
    n = int(input())
    text="["
    for i in range(n+1):
        text=text+str(n-i)
        if i!=n:
            text=text+" "
    text=text+"]"
    print(text)
    return text

In [22]:
def task_9np():
    n = int(input())
    Z = np.arange(n+1)
    Z = Z[::-1]
    return Z

In [23]:
task_9()

5
[5 4 3 2 1 0]


'[5 4 3 2 1 0]'

In [24]:
task_9np()

5


array([5, 4, 3, 2, 1, 0])

In [25]:
#Створити масив одиниць розміром n х n та створити в ньому «рамку», сформовану з 0.
def task_12(): 
    n = int(input()) 
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if i==0 or j==0 or i==n-1 or j==n-1:
                text = text + "0"
            else:
                text = text + "1"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

In [26]:
def task_12np():
    n = int(input())
    Z = np.zeros((n,n), dtype=int)
    Z[1:-1,1:-1] = 1
    return Z

In [27]:
task_12()

5
[[00000]
 [01110]
 [01110]
 [01110]
 [00000]]


'[[00000]\n [01110]\n [01110]\n [01110]\n [00000]]'

In [28]:
task_12np()

5


array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [29]:
# Розмістити на полі 8х8 нулі та одиниці в шахматному порядку, використовуючи функцію numpy tile().
def task_14():
    n = int(input())
    Z = np.tile(np.array([[0,1],[1,0]]), (n,n))
    print(Z)

In [30]:
task_14()

8
[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [31]:
# Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.
def task_15(): 
    n = int(input())  
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if j%2:
                text = text + "1"
            else:
                text = text + "0"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

In [32]:
def task_15np():
    n = int(input())
    Z = np.ones((n,n), dtype=int)
    Z[::1,::2] = 0
    return Z

In [33]:
task_15()

5
[[01010]
 [01010]
 [01010]
 [01010]
 [01010]]


'[[01010]\n [01010]\n [01010]\n [01010]\n [01010]]'

In [34]:
task_15np()

5


array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [35]:
# Згенерувати вектор із n елементів, що рівномірно розміщені на інтервалі (0,1) – тобто обидва кінці інтервалу не включені.
# Значення вивести до 3 знаків після коми.
def task_19():
    n = int(input())
    a=1/(n+1)
    count=a
    text="["
    for i in range(n):
        text=text+str('%.3f' % count)
        count = count+a
        if i!=n:
            text=text+" "
    text=text+"]"
    print(text)
    return text

In [36]:
def task_19np():
    n = int(input())
    Z = np.linspace(0,1,n+2)[1:-1]
    print(Z)

In [37]:
task_19()

10
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909 ]


'[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909 ]'

In [38]:
task_19np()

10
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
def sum_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = a[i][j]+b[i][j]
    return(c)
    
def dist_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = a[i][j]-b[i][j]
    return(c)
    
def mult_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(3))
    return(c)

def sq_matr(a):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = sum(a[i][kk] * a[kk][j] for kk in range(3))
    return(c)

a=[[7,2,0],[-7,-2,1],[1,1,0]]
b=[[0,2,3],[1,0,-2],[3,1,1]]

start_time = datetime.now()
C1=sum_matr(a,b)
A2=sq_matr(a)
B2=sq_matr(b)
C2=dist_matr(A2,B2)
R1=mult_matr(C2,C1)

print(R1)
print(datetime.now() - start_time)

[[138, 88, 68], [-154, -100, -78], [-14, -16, -12]]
0:00:00


In [48]:
a=[[7,2,0],[-7,-2,1],[1,1,0]]
b=[[0,2,3],[1,0,-2],[3,1,1]]

start_time = datetime.now()
C = np.add(a,b)
A2 = np.dot(a,a)
B2 = np.dot(b,b)
D = np.subtract(A2,B2)
R2 = np.dot(D,C)

print(R2)
print(datetime.now() - start_time)

[[ 138   88   68]
 [-154 -100  -78]
 [ -14  -16  -12]]
0:00:00


In [46]:
np.allclose(R1,R2)

True

In [49]:
def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

def getMatrixDeternminant(m):
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant(getMatrixMinor(m,0,c))
    return determinant

In [51]:
M =[[1,-3,4,-5],[1,-2,3,-4],[3,2,-5,12],[4,3,-5,5]]
print(getMatrixDeternminant(M))

36


In [53]:
M1 =np.array([[0,1,-3,4],[1,0,-2,3],[3,2,0,-5],[4,3,-5,0]])
M2=np.array([-5,-4,12,5])
R = np.linalg.solve(M1,M2)
print(R)

[ 1.  2.  1. -1.]
